### ISSUE TITLE
Build if ToDoView.ui.xml is throwing errors

### ISSUE THREAD

**Issue by Kylex87** [xtext/auto-gwt#4]
Hi,

just wanted to play with your example project and I'm stuck on the build of ToDoView.ui.xml as it seems.
Command was mvn clean install.
The filesystem is definitely accessible so I don' really understand why there is a ConnectException happening. I'm new to xtend so my only guess is, that there is some issue about creating some code in connection with ToDoView.ui.xml?

Any help would be greatly appreciated.

Greetings,
Steffen

[DEBUG] Set bootClasspath: 
[DEBUG] Set source path: /a/thoros/thoros/steffenboersig/Audit/todomvc-xtend-gwt/todomvc/src
[DEBUG] Set output path: /a/thoros/thoros/steffenboersig/Audit/todomvc-xtend-gwt/todomvc/xtend-gen
[DEBUG] Set encoding: null
[DEBUG] Set writeTraceFiles: true
[ERROR] 
ERROR:  ToDoView.xtend - 
12: Error loading file '/todomvc/src/org/eclipse/xtend/gwt/todomvc/client/ToDoView.ui.xml' : [Connection timed out]
[ERROR] 
ERROR:  ToDoView.xtend - 
12: java.net.ConnectException: Connection timed out
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:579)
    at java.net.Socket.connect(Socket.java:528)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
    at sun.net.www.http.HttpClient.New(HttpClient.java:308)
    at sun.net.www.http.HttpClient.New(HttpClient.java:326)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
    at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:643)
    at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1297)
    at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1264)
    at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:263)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1164)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1050)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:964)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
    at de.itemis.xtend.auto.gwt.UiBinderParser.<init>(UiBinderParser.java:111)
    at de.itemis.xtend.auto.gwt.WithUiBindingProcessor.createUiBinderParser(WithUiBindingProcessor.java:107)
    at de.itemis.xtend.auto.gwt.WithUiBindingProcessor.doTransform(WithUiBindingProcessor.java:78)
    at org.eclipse.xtend.lib.macro.AbstractClassProcessor.doTransform(AbstractClassProcessor.java:42)
    at org.eclipse.xtend.core.macro.AnnotationProcessor$2.run(AnnotationProcessor.java:154)
    at org.eclipse.xtend.core.macro.AnnotationProcessor.runWithCancelIndiciator(AnnotationProcessor.java:268)
    at org.eclipse.xtend.core.macro.AnnotationProcessor.inferencePhase(AnnotationProcessor.java:157)
    at org.eclipse.xtend.core.jvmmodel.XtendJvmModelInferrer$3.run(XtendJvmModelInferrer.java:216)
    at org.eclipse.xtext.xbase.resource.BatchLinkableResource.ensureJvmMembersInitialized(BatchLinkableResource.java:218)
    at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.getOrInstall(JvmModelAssociator.java:112)
    at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.sourceToTargetMap(JvmModelAssociator.java:206)
    at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.getJvmElements(JvmModelAssociator.java:337)
    at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.getPrimaryJvmElement(JvmModelAssociator.java:542)
    at org.eclipse.xtend.core.scoping.XtendImportedNamespaceScopeProvider.getContainerScope(XtendImportedNamespaceScopeProvider.java:193)
    at org.eclipse.xtend.core.scoping.XtendImportedNamespaceScopeProvider.getScope(XtendImportedNamespaceScopeProvider.java:146)
    at org.eclipse.xtext.xbase.scoping.batch.TypeScopes.createTypeScope(TypeScopes.java:59)
    at org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider.getScope(XbaseBatchScopeProvider.java:105)
    at org.eclipse.xtext.xbase.annotations.typesystem.XbaseWithAnnotationsBatchScopeProvider.getScope(XbaseWithAnnotationsBatchScopeProvider.java:53)
    at org.eclipse.xtext.linking.impl.DefaultLinkingService.getScope(DefaultLinkingService.java:59)
    at org.eclipse.xtext.linking.impl.DefaultLinkingService.getLinkedObjects(DefaultLinkingService.java:119)
    at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:250)
    at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getEObject(BatchLinkableResource.java:110)
    at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
    at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:199)
    at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:259)
    at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eResolveProxy(BasicEObjectImpl.java:1473)
    at org.eclipse.xtext.xbase.annotations.xAnnotations.impl.XAnnotationImpl.getAnnotationType(XAnnotationImpl.java:127)
    at org.eclipse.xtext.xbase.annotations.xAnnotations.impl.XAnnotationImpl.eGet(XAnnotationImpl.java:239)
    at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1011)
    at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1003)
    at org.eclipse.emf.ecore.util.EContentsEList$FeatureIteratorImpl.hasNext(EContentsEList.java:439)
    at org.eclipse.emf.ecore.util.EcoreUtil.resolveCrossReferences(EcoreUtil.java:304)
    at org.eclipse.emf.ecore.util.EcoreUtil.resolveAll(EcoreUtil.java:298)
    at org.eclipse.emf.ecore.util.EcoreUtil.resolveAll(EcoreUtil.java:283)
    at org.eclipse.emf.ecore.util.EcoreUtil.resolveAll(EcoreUtil.java:271)
    at org.eclipse.xtend.core.compiler.batch.XtendBatchCompiler.compile(XtendBatchCompiler.java:431)
    at org.eclipse.xtend.maven.AbstractXtendCompilerMojo.compile(AbstractXtendCompilerMojo.java:153)
    at org.eclipse.xtend.maven.XtendCompile.compileSources(XtendCompile.java:67)
    at org.eclipse.xtend.maven.XtendCompile.internalExecute(XtendCompile.java:59)
    at org.eclipse.xtend.maven.AbstractXtendMojo.execute(AbstractXtendMojo.java:39)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

[ERROR] 
ERROR:  ToDoView.xtend - 
63: The method text is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
21: The method or field mainSection is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
22: The method or field clearCompleted is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
23: The method element is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
24: The method element is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
25: The method or field todoStatsContainer is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
26: The method or field toggleAll is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
38: The method addKeyUpHandler is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
39: The method or field nativeKeyCode is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
45: The method or field clearCompleted is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
51: The method or field toggleAll is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
54: The method or field toggleAll is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
59: The method or field text is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
70: The method or field todoPanel is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
73: The method or field todoPanel is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
80: The method or field mainSection is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
81: The method or field todoStatsContainer is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
82: The method or field clearCompleted is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
84: The method or field remainingTodosCount is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
85: The method or field remainingTodosLabel is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
86: The method or field clearTodosCount is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoView.xtend - 
88: The method or field toggleAll is undefined for the type ToDoView
[ERROR] 
ERROR:  ToDoPresenter.xtend - 
33: Type mismatch: cannot convert from Object to String
[WARNING] 
WARNING:    ToDoView.xtend - 
62: Cannot infer type from recursive usage. Type 'Object' is used.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] org.eclipse.xtend.gwt.todomvc.parent .............. SUCCESS [0.322s]
[INFO] org.eclipse.xtend.gwt.todomvc ..................... FAILURE [2:12.760s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:13.178s
[INFO] Finished at: Thu Feb 05 17:34:53 CET 2015
[INFO] Final Memory: 62M/498M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.8.0-SNAPSHOT:compile (default) on project org.eclipse.xtend.gwt.todomvc: Error compiling xtend sources in '/a/thoros/thoros/steffenboersig/Audit/todomvc-xtend-gwt/todomvc/src'. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.8.0-SNAPSHOT:compile (default) on project org.eclipse.xtend.gwt.todomvc: Error compiling xtend sources in '/a/thoros/thoros/steffenboersig/Audit/todomvc-xtend-gwt/todomvc/src'.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error compiling xtend sources in '/a/thoros/thoros/steffenboersig/Audit/todomvc-xtend-gwt/todomvc/src'.
    at org.eclipse.xtend.maven.AbstractXtendCompilerMojo.compile(AbstractXtendCompilerMojo.java:154)
    at org.eclipse.xtend.maven.XtendCompile.compileSources(XtendCompile.java:67)
    at org.eclipse.xtend.maven.XtendCompile.internalExecute(XtendCompile.java:59)
    at org.eclipse.xtend.maven.AbstractXtendMojo.execute(AbstractXtendMojo.java:39)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 19 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.eclipse.xtend.gwt.todomvc

**Comment by svenefftinge** [comment]
This is strange. Somehow the parser is trying to open some namespace URI through http.
It’s not Xtend related, but the way we use the XML parser seems to be wrong.

I can only have a look next week, unfortunately.

You could try to debug it using plain Java and DocumentBuilder.parser with the document.

Sven

**Comment by akosyakov** [comment]
It seems that we should set "http://apache.org/xml/features/nonvalidating/load-external-dtd” feature to false to avoid resolving external DTD as here: http://stackoverflow.com/questions/155101/make-documentbuilder-parse-ignore-dtd-references.

Anton

**Comment by Kylex87** [comment]
Thank you for the hints. It could indeed be solved by adding
factory.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false)
to the UIBinderParser.

I'm now going to play with your project a little bit :)
